# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster/raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cluster/raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63luster/raft.proto\x12\x04raft\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"J\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x12\n\nleaderHint\x18\x04 \x01(\t\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x08VoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\".\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x88\x01\n\tEntryArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x05 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x06 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x07 \x01(\x05\"B\n\nEntryReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rconflictIndex\x18\x03 \x01(\x05\x32\xba\x01\n\x08RaftNode\x12%\n\x03Set\x12\x0e.raft.KeyValue\x1a\x0c.raft.Status\"\x00\x12\x1f\n\x03Get\x12\t.raft.Key\x1a\x0b.raft.Value\"\x00\x12\x30\n\x0bRequestVote\x12\x0e.raft.VoteArgs\x1a\x0f.raft.VoteReply\"\x00\x12\x34\n\rAppendEntries\x12\x0f.raft.EntryArgs\x1a\x10.raft.EntryReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster.raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=28
  _globals['_KEYVALUE']._serialized_end=66
  _globals['_KEY']._serialized_start=68
  _globals['_KEY']._serialized_end=86
  _globals['_VALUE']._serialized_start=88
  _globals['_VALUE']._serialized_end=162
  _globals['_STATUS']._serialized_start=164
  _globals['_STATUS']._serialized_end=206
  _globals['_VOTEARGS']._serialized_start=208
  _globals['_VOTEARGS']._serialized_end=253
  _globals['_VOTEREPLY']._serialized_start=255
  _globals['_VOTEREPLY']._serialized_end=301
  _globals['_ENTRYARGS']._serialized_start=304
  _globals['_ENTRYARGS']._serialized_end=440
  _globals['_ENTRYREPLY']._serialized_start=442
  _globals['_ENTRYREPLY']._serialized_end=508
  _globals['_RAFTNODE']._serialized_start=511
  _globals['_RAFTNODE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
